
DELETE FROM ACCOUNT WHERE ID = 1 OR ID = 2;
DELETE FROM ACCOUNT_KEY WHERE ID = 1 OR ID = 2;

INSERT INTO ACCOUNT_KEY VALUES(1,1);
INSERT INTO ACCOUNT_KEY VALUES(2,2);

INSERT INTO ACCOUNT VALUES(1, 2000.0, 'JOHN', 'DOE', 1);
INSERT INTO ACCOUNT VALUES(2,1000.0, 'JANE', 'DOE', 2);

SELECT * FROM ACCOUNT;